[workspace]
package.version = "0.1.0"
resolver = "3"
members = [
    "plugind",
    "plugin-example",
    "plugind-core",
    "plugind-macros",
    "pluginctl",
    "plugind-http"
]

[profile.release]
lto = true
strip = true
opt-level = 3
