[package]
name = "plugind-macros"
version.workspace = true
edition = "2024"

[dependencies]
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "2.0", features = ["full"] }
futures = "0.3"

[lib]
proc-macro = true